# Generated by Django 4.2.1 on 2023-10-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MFDP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='team',
            old_name='executive_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='team',
            name='staff_image',
        ),
    ]
